version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: evacuation-api
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DB=${REDIS_DB:-0}
      - REDIS_TTL=${REDIS_TTL:-300}
      - REDIS_TLS=${REDIS_TLS:-true}
      - JWT_SECRET=${JWT_SECRET}
      - API_KEY=${API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FILE_PATH=${LOG_FILE_PATH}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS}
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - CORS_CREDENTIALS=${CORS_CREDENTIALS:-true}
      - HEALTH_CHECK_ENDPOINT=${HEALTH_CHECK_ENDPOINT}
      - METRICS_ENDPOINT=${METRICS_ENDPOINT}
      - MAX_REQUEST_SIZE=${MAX_REQUEST_SIZE}
      - REQUEST_TIMEOUT=${REQUEST_TIMEOUT}
    networks:
      - evacuation_network
    restart: unless-stopped

networks:
  evacuation_network:
    driver: bridge
