# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - nestjs2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: evacution.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_6C02DA3B5AE44A1B8307D14E36F75778 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_C3C9362243FE45B98673C0AEFBC94A96 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: evacution.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_6C02DA3B5AE44A1B8307D14E36F75778 }}/evacuation-api:v1
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    
    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_71D936F7E24640F0B1E1A19EF65F2B70 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6769FA382AF946DC922C22586A7C6912 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AC251F5AF37C44D099F3681802593A35 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'nestjs2'
          slot-name: 'Production'
          images: 'evacution.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_6C02DA3B5AE44A1B8307D14E36F75778 }}/evacuation-api:v1'
          