# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - nesjsapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: evacution.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_41B15BC55AED4717A4838DBB1E5BF36C }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_C05BED1A0D054D9882CA10789E2AE8BC }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: evacution.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_41B15BC55AED4717A4838DBB1E5BF36C }}/evacution/evacuation-api:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    
    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C50E8714292247EFA77118C1ADDF9F77 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6CA897DA33C64515A1B26C5537C44284 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B1F9DCA0E1134EF586AB03D1C44DE0DE }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'nesjsapp'
          slot-name: 'Production'
          images: 'evacution.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_41B15BC55AED4717A4838DBB1E5BF36C }}/evacuation-api:${{ github.sha }}'
          